compiler = gcc
standard = -std=c99
flags = -Wall

bit64:
	$(compiler) $(standard) -m64 src/x64/*.c $(flags) -o src/x64/SilentVM

bit32:
	$(compiler) $(standard) -m32 src/x32/*.c $(flags) -o src/x32/SilentVM



